//! Symbol glyph tables extracted from omp `symbols.ts` (three presets:
//! unicode / nerd / ascii). Keys are stable across presets; values are
//! the glyph strings. Do not hand-edit — regenerate with `gen_symbols.py`.

/// Symbol preset identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SymbolPreset {
    Unicode,
    Nerd,
    Ascii,
}

impl SymbolPreset {
    /// Parse a preset name; `None` for anything else.
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "unicode" => Some(SymbolPreset::Unicode),
            "nerd" => Some(SymbolPreset::Nerd),
            "ascii" => Some(SymbolPreset::Ascii),
            _ => None,
        }
    }
}

/// All valid symbol preset names, in canonical order.
pub const SYMBOL_PRESET_NAMES: &[&str] = &["unicode", "nerd", "ascii"];

/// UNICODE_SYMBOLS — key → symbol glyph.
pub static UNICODE_SYMBOLS: &[(&str, &str)] = &[
    ("status.success", "✔"),
    ("status.error", "✘"),
    ("status.warning", "⚠"),
    ("status.info", "ⓘ"),
    ("status.pending", "⏳"),
    ("status.disabled", "⦸"),
    ("status.enabled", "●"),
    ("status.running", "⟳"),
    ("status.shadowed", "○"),
    ("status.aborted", "⏹"),
    ("status.done", "•"),
    ("nav.cursor", "❯"),
    ("nav.selected", "➤"),
    ("nav.expand", "▸"),
    ("nav.collapse", "▾"),
    ("nav.back", "⟵"),
    ("tree.branch", "├─"),
    ("tree.last", "└─"),
    ("tree.vertical", "│"),
    ("tree.horizontal", "─"),
    ("tree.hook", "└"),
    ("progress.filled", "━"),
    ("progress.empty", "─"),
    ("scroll.track", "│"),
    ("scroll.thumb", "█"),
    ("context.speculation", "╎"),
    ("context.compaction", "┃"),
    ("boxRound.topLeft", "╭"),
    ("boxRound.topRight", "╮"),
    ("boxRound.bottomLeft", "╰"),
    ("boxRound.bottomRight", "╯"),
    ("boxRound.horizontal", "─"),
    ("boxRound.vertical", "│"),
    ("boxSharp.topLeft", "┌"),
    ("boxSharp.topRight", "┐"),
    ("boxSharp.bottomLeft", "└"),
    ("boxSharp.bottomRight", "┘"),
    ("boxSharp.horizontal", "─"),
    ("boxSharp.vertical", "│"),
    ("boxSharp.cross", "┼"),
    ("boxSharp.teeDown", "┬"),
    ("boxSharp.teeUp", "┴"),
    ("boxSharp.teeRight", "├"),
    ("boxSharp.teeLeft", "┤"),
    ("sep.powerline", "▕"),
    ("sep.powerlineThin", "┆"),
    ("sep.powerlineLeft", "▶"),
    ("sep.powerlineRight", "◀"),
    ("sep.powerlineThinLeft", ">"),
    ("sep.powerlineThinRight", "<"),
    ("sep.block", "▌"),
    ("sep.space", " "),
    ("sep.asciiLeft", ">"),
    ("sep.asciiRight", "<"),
    ("sep.dot", " · "),
    ("sep.slash", " / "),
    ("sep.pipe", " │ "),
    ("icon.model", "⬢"),
    ("icon.plan", "🗺"),
    ("icon.prewalk", "🏃"),
    ("icon.goal", "🎯"),
    ("icon.pause", "⏸"),
    ("icon.loop", "↻"),
    ("icon.folder", "📁"),
    ("icon.worktree", "🌳"),
    ("icon.search", "🔍"),
    ("icon.scratchFolder", "🗑"),
    ("icon.file", "📄"),
    ("icon.git", "⎇"),
    ("icon.branch", "⑂"),
    ("icon.pr", "⤴"),
    ("icon.pin", "📌"),
    ("icon.tokens", "🪙"),
    ("icon.context", "◫"),
    ("icon.cost", "💲"),
    ("icon.subscription", "(sub)"),
    ("icon.advisor", "👁"),
    ("icon.time", "⏱"),
    ("icon.pi", "π"),
    ("icon.ghost", "👻"),
    ("icon.agents", "👥"),
    ("icon.job", "⚙"),
    ("icon.cache", "💾"),
    ("icon.cacheMiss", "⊘"),
    ("icon.input", "⤵"),
    ("icon.output", "⤴"),
    ("icon.throughput", "⚡"),
    ("icon.host", "🖥"),
    ("icon.session", "🆔"),
    ("icon.package", "📦"),
    ("icon.warning", "⚠"),
    ("icon.rewind", "↶"),
    ("icon.auto", "⟲"),
    ("icon.fast", "⚡"),
    ("icon.extensionSkill", "✦"),
    ("icon.extensionTool", "🛠"),
    ("icon.extensionSlashCommand", "⌘"),
    ("icon.extensionMcp", "🔌"),
    ("icon.extensionRule", "⚖"),
    ("icon.extensionHook", "🪝"),
    ("icon.extensionPrompt", "✎"),
    ("icon.extensionContextFile", "📎"),
    ("icon.extensionInstruction", "📘"),
    ("cmd.action", "❯"),
    ("cmd.prompt", "✎"),
    ("cmd.extension", "🧩"),
    ("cmd.settings", "🎛"),
    ("cmd.gear", "⚙"),
    ("cmd.shield", "🛡"),
    ("cmd.wave", "∿"),
    ("cmd.compass", "🧭"),
    ("cmd.inbox", "📥"),
    ("cmd.swap", "⇄"),
    ("cmd.expand", "⤢"),
    ("cmd.computer", "🖥"),
    ("cmd.eye", "👁"),
    ("cmd.todo", "☑"),
    ("cmd.stats", "📊"),
    ("cmd.news", "📰"),
    ("cmd.keyboard", "⌨"),
    ("cmd.export", "📤"),
    ("cmd.clipboard", "📋"),
    ("cmd.share", "↗"),
    ("cmd.broadcast", "📡"),
    ("cmd.globe", "🌐"),
    ("cmd.copy", "⧉"),
    ("cmd.plus", "✚"),
    ("cmd.restart", "↻"),
    ("cmd.eraser", "🧹"),
    ("cmd.trash", "🗑"),
    ("cmd.compress", "🗜"),
    ("cmd.vibrate", "📳"),
    ("cmd.handoff", "➦"),
    ("cmd.history", "🕘"),
    ("cmd.question", "❓"),
    ("cmd.rocket", "🚀"),
    ("cmd.stethoscope", "🩺"),
    ("cmd.redo", "🔁"),
    ("cmd.bug", "🐛"),
    ("cmd.memory", "🧠"),
    ("cmd.pencil", "✏"),
    ("cmd.folderMove", "📂"),
    ("cmd.folderPlus", "📁"),
    ("cmd.folderMinus", "📁"),
    ("cmd.hammer", "🔨"),
    ("cmd.power", "⏻"),
    ("cmd.cart", "🛒"),
    ("icon.mic", "🎤"),
    ("icon.camera", "📷"),
    ("thinking.minimal", "○ min"),
    ("thinking.low", "◔ low"),
    ("thinking.medium", "◑ med"),
    ("thinking.high", "◒ high"),
    ("thinking.xhigh", "◕ xhigh"),
    ("thinking.max", "◉ max"),
    ("thinking.autoPending", "⟳"),
    ("checkbox.checked", "☑"),
    ("checkbox.unchecked", "☐"),
    ("radio.selected", "◉"),
    ("radio.unselected", "○"),
    ("format.bullet", "•"),
    ("format.dash", "—"),
    ("format.bracketLeft", "⟦"),
    ("format.bracketRight", "⟧"),
    ("md.quoteBorder", "▏"),
    ("md.hrChar", "─"),
    ("md.bullet", "•"),
    ("md.colorSwatch", "■"),
    ("advisor.rail", "▎"),
    ("lang.default", "⌘"),
    ("lang.typescript", "🟦"),
    ("lang.javascript", "🟨"),
    ("lang.python", "🐍"),
    ("lang.rust", "🦀"),
    ("lang.go", "🐹"),
    ("lang.java", "☕"),
    ("lang.c", "Ⓒ"),
    ("lang.cpp", "➕"),
    ("lang.csharp", "♯"),
    ("lang.ruby", "💎"),
    ("lang.julia", "Ⓙ"),
    ("lang.php", "🐘"),
    ("lang.swift", "🕊"),
    ("lang.kotlin", "🅺"),
    ("lang.shell", "💻"),
    ("lang.html", "🌐"),
    ("lang.css", "🎨"),
    ("lang.json", "🧾"),
    ("lang.yaml", "📋"),
    ("lang.markdown", "📝"),
    ("lang.sql", "🗄"),
    ("lang.docker", "🐳"),
    ("lang.lua", "🌙"),
    ("lang.text", "🗒"),
    ("lang.env", "🔧"),
    ("lang.toml", "🧾"),
    ("lang.xml", "⟨⟩"),
    ("lang.ini", "⚙"),
    ("lang.conf", "⚙"),
    ("lang.log", "📜"),
    ("lang.csv", "📑"),
    ("lang.tsv", "📑"),
    ("lang.image", "🖼"),
    ("lang.pdf", "📕"),
    ("lang.archive", "🗜"),
    ("lang.binary", "⚙"),
    ("chip.image", "🖼"),
    ("chip.paste", "📄"),
    ("tab.appearance", "🎨"),
    ("tab.model", "🤖"),
    ("tab.interaction", "⌨"),
    ("tab.context", "📋"),
    ("tab.files", "📁"),
    ("tab.shell", "💻"),
    ("tab.tools", "🔧"),
    ("tab.memory", "🧠"),
    ("tab.tasks", "📦"),
    ("tab.providers", "🌐"),
    ("tool.write", "✎"),
    ("tool.edit", "✎"),
    ("tool.bash", "❯"),
    ("tool.ssh", "⇄"),
    ("tool.lsp", "💡"),
    ("tool.gh", "⎇"),
    ("tool.webSearch", "⌕"),
    ("tool.exa", "🔭"),
    ("tool.browser", "🌐"),
    ("tool.eval", "▶"),
    ("tool.debug", "🐞"),
    ("tool.mcp", "🔌"),
    ("tool.job", "⚙"),
    ("tool.launch", "🚀"),
    ("tool.task", "⇶"),
    ("tool.todo", "☑"),
    ("tool.memory", "🧠"),
    ("tool.ask", "?"),
    ("tool.resolve", "✓"),
    ("tool.review", "◉"),
    ("tool.inspectImage", "🖼"),
    ("tool.goal", "◎"),
    ("tool.irc", "✉"),
    ("tool.delete", "🗑"),
    ("tool.move", "➜"),
];

/// NERD_SYMBOLS — key → symbol glyph.
pub static NERD_SYMBOLS: &[(&str, &str)] = &[
    ("status.success", "\u{f00c}"),
    ("status.error", "\u{f00d}"),
    ("status.warning", "\u{f12a}"),
    ("status.info", "\u{f129}"),
    ("status.pending", "\u{f254}"),
    ("status.disabled", "\u{f05e}"),
    ("status.enabled", "\u{f111}"),
    ("status.running", "\u{f110}"),
    ("status.shadowed", "\u{f10c}"),
    ("status.aborted", "\u{f04d}"),
    ("status.done", "•"),
    ("nav.cursor", "\u{f054}"),
    ("nav.selected", "\u{f178}"),
    ("nav.expand", "\u{f0da}"),
    ("nav.collapse", "\u{f0d7}"),
    ("nav.back", "\u{f060}"),
    ("tree.branch", "├─"),
    ("tree.last", "└─"),
    ("tree.vertical", "│"),
    ("tree.horizontal", "─"),
    ("tree.hook", "└"),
    ("progress.filled", "━"),
    ("progress.empty", "─"),
    ("scroll.track", "│"),
    ("scroll.thumb", "█"),
    ("context.speculation", "\u{f055d}"),
    ("context.compaction", "\u{f0068}"),
    ("boxRound.topLeft", "╭"),
    ("boxRound.topRight", "╮"),
    ("boxRound.bottomLeft", "╰"),
    ("boxRound.bottomRight", "╯"),
    ("boxRound.horizontal", "─"),
    ("boxRound.vertical", "│"),
    ("boxSharp.topLeft", "┌"),
    ("boxSharp.topRight", "┐"),
    ("boxSharp.bottomLeft", "└"),
    ("boxSharp.bottomRight", "┘"),
    ("boxSharp.horizontal", "─"),
    ("boxSharp.vertical", "│"),
    ("boxSharp.cross", "┼"),
    ("boxSharp.teeDown", "┬"),
    ("boxSharp.teeUp", "┴"),
    ("boxSharp.teeRight", "├"),
    ("boxSharp.teeLeft", "┤"),
    ("sep.powerline", "\u{e0b0}"),
    ("sep.powerlineThin", "\u{e0b1}"),
    ("sep.powerlineLeft", "\u{e0b0}"),
    ("sep.powerlineRight", "\u{e0b2}"),
    ("sep.powerlineThinLeft", "\u{e0b1}"),
    ("sep.powerlineThinRight", "\u{e0b3}"),
    ("sep.block", "█"),
    ("sep.space", " "),
    ("sep.asciiLeft", ">"),
    ("sep.asciiRight", "<"),
    ("sep.dot", " · "),
    ("sep.slash", "\u{e0bb}"),
    ("sep.pipe", "\u{e0b3}"),
    ("icon.model", "\u{ec19}"),
    ("icon.plan", "\u{f2d2}"),
    ("icon.prewalk", "\u{f29d}"),
    ("icon.goal", "\u{f140}"),
    ("icon.pause", "\u{f04c}"),
    ("icon.loop", "\u{f021}"),
    ("icon.folder", "\u{f115}"),
    ("icon.worktree", "\u{f0e8}"),
    ("icon.search", "\u{f002}"),
    ("icon.scratchFolder", "\u{f014}"),
    ("icon.file", "\u{f15b}"),
    ("icon.git", "\u{f1d3}"),
    ("icon.branch", "\u{f126}"),
    ("icon.pr", "\u{ea64}"),
    ("icon.pin", "\u{f08d}"),
    ("icon.tokens", "\u{e26b}"),
    ("icon.context", "\u{e70f}"),
    ("icon.cost", "\u{f155}"),
    ("icon.subscription", "\u{f067a}"),
    ("icon.advisor", "\u{ea70}"),
    ("icon.time", "\u{f017}"),
    ("icon.pi", "\u{e22c}"),
    ("icon.ghost", "\u{f02a0}"),
    ("icon.agents", "\u{f0c0}"),
    ("icon.job", "\u{f013}"),
    ("icon.cache", "\u{f1c0}"),
    ("icon.cacheMiss", "\u{f05e}"),
    ("icon.input", "\u{f090}"),
    ("icon.output", "\u{f08b}"),
    ("icon.throughput", "\u{f0e4}"),
    ("icon.host", "\u{f109}"),
    ("icon.session", "\u{f0051}"),
    ("icon.package", "\u{f487}"),
    ("icon.warning", "\u{f071}"),
    ("icon.rewind", "\u{f0e2}"),
    ("icon.auto", "\u{f0068}"),
    ("icon.fast", "\u{f0e7}"),
    ("icon.extensionSkill", "\u{f0eb}"),
    ("icon.extensionTool", "\u{f0ad}"),
    ("icon.extensionSlashCommand", "\u{f120}"),
    ("icon.extensionMcp", "\u{f1e6}"),
    ("icon.extensionRule", "\u{f0e3}"),
    ("icon.extensionHook", "\u{f0c1}"),
    ("icon.extensionPrompt", "\u{f075}"),
    ("icon.extensionContextFile", "\u{f0f6}"),
    ("icon.extensionInstruction", "\u{f02d}"),
    ("cmd.action", "\u{ea85}"),
    ("cmd.prompt", "\u{f0eab}"),
    ("cmd.extension", "\u{f12e}"),
    ("cmd.settings", "\u{f1de}"),
    ("cmd.gear", "\u{eb51}"),
    ("cmd.shield", "\u{f132}"),
    ("cmd.wave", "\u{f095b}"),
    ("cmd.compass", "\u{f14e}"),
    ("cmd.inbox", "\u{f01c}"),
    ("cmd.swap", "\u{f04e1}"),
    ("cmd.expand", "\u{f004c}"),
    ("cmd.computer", "\u{f108}"),
    ("cmd.eye", "\u{f06e}"),
    ("cmd.todo", "\u{f0ae}"),
    ("cmd.stats", "\u{f080}"),
    ("cmd.news", "\u{f1ea}"),
    ("cmd.keyboard", "\u{f11c}"),
    ("cmd.export", "\u{f08e}"),
    ("cmd.clipboard", "\u{f0ea}"),
    ("cmd.share", "\u{f1e0}"),
    ("cmd.broadcast", "\u{eaad}"),
    ("cmd.globe", "\u{f0ac}"),
    ("cmd.copy", "\u{f0c5}"),
    ("cmd.plus", "\u{f055}"),
    ("cmd.restart", "\u{f0709}"),
    ("cmd.eraser", "\u{f12d}"),
    ("cmd.trash", "\u{f014}"),
    ("cmd.compress", "\u{f066}"),
    ("cmd.vibrate", "\u{f0566}"),
    ("cmd.handoff", "\u{f064}"),
    ("cmd.history", "\u{f02da}"),
    ("cmd.question", "\u{f059}"),
    ("cmd.rocket", "\u{f135}"),
    ("cmd.stethoscope", "\u{f0f1}"),
    ("cmd.redo", "\u{f044e}"),
    ("cmd.bug", "\u{f188}"),
    ("cmd.memory", "\u{f035b}"),
    ("cmd.pencil", "\u{f044}"),
    ("cmd.folderMove", "\u{f0252}"),
    ("cmd.folderPlus", "\u{f0257}"),
    ("cmd.folderMinus", "\u{f0258}"),
    ("cmd.hammer", "\u{f08ea}"),
    ("cmd.power", "\u{f011}"),
    ("cmd.cart", "\u{f07a}"),
    ("icon.mic", "\u{f130}"),
    ("icon.camera", "\u{f083}"),
    ("thinking.minimal", "\u{f0a9e} min"),
    ("thinking.low", "\u{f0a9f} low"),
    ("thinking.medium", "\u{f0aa1} med"),
    ("thinking.high", "\u{f0aa3} high"),
    ("thinking.xhigh", "\u{f0aa5} xhi"),
    ("thinking.max", "\u{f06d} max"),
    ("thinking.autoPending", "\u{f074}"),
    ("checkbox.checked", "\u{f14a}"),
    ("checkbox.unchecked", "\u{f096}"),
    ("radio.selected", "\u{f192}"),
    ("radio.unselected", "\u{f10c}"),
    ("format.bullet", "\u{f111}"),
    ("format.dash", "–"),
    ("format.bracketLeft", "⟨"),
    ("format.bracketRight", "⟩"),
    ("md.quoteBorder", "│"),
    ("md.hrChar", "─"),
    ("md.bullet", "\u{f111}"),
    ("md.colorSwatch", "■"),
    ("advisor.rail", "▎"),
    ("lang.default", ""),
    ("lang.typescript", "\u{e628}"),
    ("lang.javascript", "\u{e60c}"),
    ("lang.python", "\u{e606}"),
    ("lang.rust", "\u{e7a8}"),
    ("lang.go", "\u{e627}"),
    ("lang.java", "\u{e738}"),
    ("lang.c", "\u{e61e}"),
    ("lang.cpp", "\u{e61d}"),
    ("lang.csharp", "\u{e7b2}"),
    ("lang.ruby", "\u{e791}"),
    ("lang.julia", "\u{e624}"),
    ("lang.php", "\u{e608}"),
    ("lang.swift", "\u{e755}"),
    ("lang.kotlin", "\u{e634}"),
    ("lang.shell", "\u{e795}"),
    ("lang.html", "\u{e736}"),
    ("lang.css", "\u{e749}"),
    ("lang.json", "\u{e60b}"),
    ("lang.yaml", "\u{e615}"),
    ("lang.markdown", "\u{e609}"),
    ("lang.sql", "\u{e706}"),
    ("lang.docker", "\u{e7b0}"),
    ("lang.lua", "\u{e620}"),
    ("lang.text", "\u{e612}"),
    ("lang.env", "\u{e615}"),
    ("lang.toml", "\u{e615}"),
    ("lang.xml", "\u{f05c0}"),
    ("lang.ini", "\u{e615}"),
    ("lang.conf", "\u{e615}"),
    ("lang.log", "\u{f0331}"),
    ("lang.csv", "\u{f021b}"),
    ("lang.tsv", "\u{f021b}"),
    ("lang.image", "\u{f021f}"),
    ("lang.pdf", "\u{f0226}"),
    ("lang.archive", "\u{f187}"),
    ("lang.binary", "\u{f019a}"),
    ("chip.image", "\u{f03e}"),
    ("chip.paste", "\u{f15c}"),
    ("tab.appearance", "󰃣"),
    ("tab.model", "󰚩"),
    ("tab.interaction", "󰌌"),
    ("tab.context", "󰘸"),
    ("tab.files", "󰈔"),
    ("tab.shell", "󰆍"),
    ("tab.tools", "󰠭"),
    ("tab.memory", "󰧑"),
    ("tab.tasks", "󰐱"),
    ("tab.providers", "󰖟"),
    ("tool.write", "\u{ea7f}"),
    ("tool.edit", "\u{ea73}"),
    ("tool.bash", "\u{ebca}"),
    ("tool.ssh", "\u{eb3a}"),
    ("tool.lsp", "\u{ea61}"),
    ("tool.gh", "\u{ea84}"),
    ("tool.webSearch", "\u{eb01}"),
    ("tool.exa", "\u{eb68}"),
    ("tool.browser", "\u{eaae}"),
    ("tool.eval", "\u{ebaf}"),
    ("tool.debug", "\u{ead8}"),
    ("tool.mcp", "\u{eb2d}"),
    ("tool.job", "\u{eba2}"),
    ("tool.launch", "\u{f135}"),
    ("tool.task", "\u{f4a0}"),
    ("tool.todo", "\u{eab3}"),
    ("tool.memory", "\u{eace}"),
    ("tool.ask", "\u{eac7}"),
    ("tool.resolve", "\u{ebb1}"),
    ("tool.review", "\u{ea70}"),
    ("tool.inspectImage", "\u{eaea}"),
    ("tool.goal", "\u{ebf8}"),
    ("tool.irc", "\u{f086}"),
    ("tool.delete", "\u{f12d}"),
    ("tool.move", "\u{f061}"),
];

/// ASCII_SYMBOLS — key → symbol glyph.
pub static ASCII_SYMBOLS: &[(&str, &str)] = &[
    ("status.success", "[ok]"),
    ("status.error", "[!!]"),
    ("status.warning", "[!]"),
    ("status.info", "[i]"),
    ("status.pending", "[*]"),
    ("status.disabled", "[ ]"),
    ("status.enabled", "[x]"),
    ("status.running", "[~]"),
    ("status.shadowed", "[/]"),
    ("status.aborted", "[-]"),
    ("status.done", "*"),
    ("nav.cursor", ">"),
    ("nav.selected", "->"),
    ("nav.expand", "+"),
    ("nav.collapse", "-"),
    ("nav.back", "<-"),
    ("tree.branch", "|--"),
    ("tree.last", "'--"),
    ("tree.vertical", "|"),
    ("tree.horizontal", "-"),
    ("tree.hook", "`-"),
    ("progress.filled", "="),
    ("progress.empty", "-"),
    ("scroll.track", "|"),
    ("scroll.thumb", "#"),
    ("context.speculation", ":"),
    ("context.compaction", "|"),
    ("boxRound.topLeft", "+"),
    ("boxRound.topRight", "+"),
    ("boxRound.bottomLeft", "+"),
    ("boxRound.bottomRight", "+"),
    ("boxRound.horizontal", "-"),
    ("boxRound.vertical", "|"),
    ("boxSharp.topLeft", "+"),
    ("boxSharp.topRight", "+"),
    ("boxSharp.bottomLeft", "+"),
    ("boxSharp.bottomRight", "+"),
    ("boxSharp.horizontal", "-"),
    ("boxSharp.vertical", "|"),
    ("boxSharp.cross", "+"),
    ("boxSharp.teeDown", "+"),
    ("boxSharp.teeUp", "+"),
    ("boxSharp.teeRight", "+"),
    ("boxSharp.teeLeft", "+"),
    ("sep.powerline", ">"),
    ("sep.powerlineThin", ">"),
    ("sep.powerlineLeft", ">"),
    ("sep.powerlineRight", "<"),
    ("sep.powerlineThinLeft", ">"),
    ("sep.powerlineThinRight", "<"),
    ("sep.block", "#"),
    ("sep.space", " "),
    ("sep.asciiLeft", ">"),
    ("sep.asciiRight", "<"),
    ("sep.dot", " - "),
    ("sep.slash", " / "),
    ("sep.pipe", " | "),
    ("icon.model", "[M]"),
    ("icon.plan", "plan"),
    ("icon.prewalk", "prewalk"),
    ("icon.goal", "goal"),
    ("icon.pause", "||"),
    ("icon.loop", "loop"),
    ("icon.folder", "[D]"),
    ("icon.worktree", "[wt]"),
    ("icon.search", "[/]"),
    ("icon.scratchFolder", "[T]"),
    ("icon.file", "[F]"),
    ("icon.git", "git:"),
    ("icon.branch", "@"),
    ("icon.pr", "PR"),
    ("icon.pin", "*"),
    ("icon.tokens", "tok:"),
    ("icon.context", "ctx:"),
    ("icon.cost", "$"),
    ("icon.subscription", "(sub)"),
    ("icon.advisor", "(adv)"),
    ("icon.time", "t:"),
    ("icon.pi", "pi"),
    ("icon.ghost", "@"),
    ("icon.agents", "AG"),
    ("icon.job", "bg"),
    ("icon.cache", "cache"),
    ("icon.cacheMiss", "!"),
    ("icon.input", "in:"),
    ("icon.output", "out:"),
    ("icon.throughput", "tok/s:"),
    ("icon.host", "host"),
    ("icon.session", "id"),
    ("icon.package", "[P]"),
    ("icon.warning", "[!]"),
    ("icon.rewind", "<-"),
    ("icon.auto", "[A]"),
    ("icon.fast", ">>"),
    ("icon.extensionSkill", "SK"),
    ("icon.extensionTool", "TL"),
    ("icon.extensionSlashCommand", "/"),
    ("icon.extensionMcp", "MCP"),
    ("icon.extensionRule", "RL"),
    ("icon.extensionHook", "HK"),
    ("icon.extensionPrompt", "PR"),
    ("icon.extensionContextFile", "CF"),
    ("icon.extensionInstruction", "IN"),
    ("cmd.action", ""),
    ("cmd.prompt", ""),
    ("cmd.extension", ""),
    ("cmd.settings", ""),
    ("cmd.gear", ""),
    ("cmd.shield", ""),
    ("cmd.wave", ""),
    ("cmd.compass", ""),
    ("cmd.inbox", ""),
    ("cmd.swap", ""),
    ("cmd.expand", ""),
    ("cmd.computer", ""),
    ("cmd.eye", ""),
    ("cmd.todo", ""),
    ("cmd.stats", ""),
    ("cmd.news", ""),
    ("cmd.keyboard", ""),
    ("cmd.export", ""),
    ("cmd.clipboard", ""),
    ("cmd.share", ""),
    ("cmd.broadcast", ""),
    ("cmd.globe", ""),
    ("cmd.copy", ""),
    ("cmd.plus", ""),
    ("cmd.restart", ""),
    ("cmd.eraser", ""),
    ("cmd.trash", ""),
    ("cmd.compress", ""),
    ("cmd.vibrate", ""),
    ("cmd.handoff", ""),
    ("cmd.history", ""),
    ("cmd.question", ""),
    ("cmd.rocket", ""),
    ("cmd.stethoscope", ""),
    ("cmd.redo", ""),
    ("cmd.bug", ""),
    ("cmd.memory", ""),
    ("cmd.pencil", ""),
    ("cmd.folderMove", ""),
    ("cmd.folderPlus", ""),
    ("cmd.folderMinus", ""),
    ("cmd.hammer", ""),
    ("cmd.power", ""),
    ("cmd.cart", ""),
    ("icon.mic", "MIC"),
    ("icon.camera", "[o]"),
    ("thinking.minimal", "[min]"),
    ("thinking.low", "[low]"),
    ("thinking.medium", "[med]"),
    ("thinking.high", "[high]"),
    ("thinking.xhigh", "[xhi]"),
    ("thinking.max", "[max]"),
    ("thinking.autoPending", "[~]"),
    ("checkbox.checked", "[x]"),
    ("checkbox.unchecked", "[ ]"),
    ("radio.selected", "(o)"),
    ("radio.unselected", "( )"),
    ("format.bullet", "*"),
    ("format.dash", "-"),
    ("format.bracketLeft", "["),
    ("format.bracketRight", "]"),
    ("md.quoteBorder", "|"),
    ("md.hrChar", "-"),
    ("md.bullet", "*"),
    ("md.colorSwatch", "[]"),
    ("advisor.rail", "|"),
    ("lang.default", "code"),
    ("lang.typescript", "ts"),
    ("lang.javascript", "js"),
    ("lang.python", "py"),
    ("lang.rust", "rs"),
    ("lang.go", "go"),
    ("lang.java", "java"),
    ("lang.c", "c"),
    ("lang.cpp", "cpp"),
    ("lang.csharp", "cs"),
    ("lang.ruby", "rb"),
    ("lang.julia", "jl"),
    ("lang.php", "php"),
    ("lang.swift", "swift"),
    ("lang.kotlin", "kt"),
    ("lang.shell", "sh"),
    ("lang.html", "html"),
    ("lang.css", "css"),
    ("lang.json", "json"),
    ("lang.yaml", "yaml"),
    ("lang.markdown", "md"),
    ("lang.sql", "sql"),
    ("lang.docker", "docker"),
    ("lang.lua", "lua"),
    ("lang.text", "txt"),
    ("lang.env", "env"),
    ("lang.toml", "toml"),
    ("lang.xml", "xml"),
    ("lang.ini", "ini"),
    ("lang.conf", "conf"),
    ("lang.log", "log"),
    ("lang.csv", "csv"),
    ("lang.tsv", "tsv"),
    ("lang.image", "img"),
    ("lang.pdf", "pdf"),
    ("lang.archive", "zip"),
    ("lang.binary", "bin"),
    ("chip.image", "img"),
    ("chip.paste", "txt"),
    ("tab.appearance", "[A]"),
    ("tab.model", "[M]"),
    ("tab.interaction", "[I]"),
    ("tab.context", "[X]"),
    ("tab.files", "[F]"),
    ("tab.shell", "[S]"),
    ("tab.tools", "[T]"),
    ("tab.memory", "[Y]"),
    ("tab.tasks", "[K]"),
    ("tab.providers", "[P]"),
    ("tool.write", "+f"),
    ("tool.edit", "~"),
    ("tool.bash", "$"),
    ("tool.ssh", "ssh"),
    ("tool.lsp", "lsp"),
    ("tool.gh", "gh"),
    ("tool.webSearch", "web"),
    ("tool.exa", "exa"),
    ("tool.browser", "[w]"),
    ("tool.eval", ">_"),
    ("tool.debug", "dbg"),
    ("tool.mcp", "<>"),
    ("tool.job", "job"),
    ("tool.launch", "run"),
    ("tool.task", ">>>"),
    ("tool.todo", "[x]"),
    ("tool.memory", "mem"),
    ("tool.ask", "[?]"),
    ("tool.resolve", "[v]"),
    ("tool.review", "rev"),
    ("tool.inspectImage", "[i]"),
    ("tool.goal", "(o)"),
    ("tool.irc", "irc"),
    ("tool.delete", "rm"),
    ("tool.move", "mv"),
];

/// Spinner animation frames per preset, keyed by spinner type.
/// `status` = primary activity indicator; `activity` = secondary.
pub struct SpinnerFrames {
    pub status: &'static [&'static str],
    pub activity: &'static [&'static str],
}

pub static SPINNER_UNICODE: SpinnerFrames = SpinnerFrames {
    status: &["⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"],
    activity: &["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
};

pub static SPINNER_NERD: SpinnerFrames = SpinnerFrames {
    status: &["󱑖", "󱑋", "󱑌", "󱑍", "󱑎", "󱑏", "󱑐", "󱑑", "󱑒", "󱑓", "󱑔", "󱑕"],
    activity: &["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
};

pub static SPINNER_ASCII: SpinnerFrames = SpinnerFrames {
    status: &["|", "/", "-", "\\"],
    activity: &["-", "\\", "|", "/"],
};
